# Generated by Django 2.2.4 on 2019-08-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='core_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sku',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
