# Generated by Django 2.2.4 on 2019-08-13 20:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190809_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='cor',
            new_name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='sku',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
