# Generated by Django 2.2.4 on 2020-06-01 12:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200531_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgaopublico',
            name='endereco_apelido',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='orgaopublico',
            name='localizacao_geografica',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Pontos de Latitude e Longitude', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='endereco_apelido',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='localizacao_geografica',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Pontos de Latitude e Longitude', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='pontocoleta',
            name='endereco_apelido',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='pontocoleta',
            name='localizacao_geografica',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Pontos de Latitude e Longitude', null=True, srid=4326),
        ),
    ]
