# Generated by Django 2.2.4 on 2020-06-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200601_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='pontuacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
